package main;

public enum RandomKey {
	AGENT_RANDOM,
	TASK_RANDOM,
	DEADLINE_RANDOM,
	AGENT_MAP_RANDOM,
	DEADLINE_SORT_RANDOM,
	REQUIRE_SORT_RANDOM,
	POISSON_RANDOM,
	POISSON_RANDOM_2,
	SORT_RANDOM_1,
	SORT_RANDOM_2,
	SORT_RANDOM_3,
	SORT_RANDOM_4,
	EPSILON_GREEDY_RANDOM_1,
	EPSILON_GREEDY_RANDOM_2,
	EPSILON_GREEDY_RANDOM_3,
	SHUFFLE_RANDOM_1,
	SHUFFLE_RANDOM_2,
	SELECT_RANDOM_1,
	SELECT_RANDOM_2,
	SELECT_RANDOM_3,
	SELECT_RANDOM_4,
	SELECT_RANDOM_5,
	REQUIRE_RANDOM,
	GREEDY_RANDOM;
}